### ISSUE TITLE
Add 'Interpolation' section

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#13]
At least a simple example of using interpolation:

- [ ] **AngularJS:**
`{{ }}` `ng-bind` `ng-cloak`

- [ ] **Angular:**
`{{ }}`
https://angular.io/guide/template-syntax#interpolation

- [ ] **React:**
`{ }`

Preferably also with links to docs.

**Comment by varughese** [comment]
I can pick this up

**Comment by feimosi** [comment]
Perfect! 👍

**Comment by feimosi** [comment]
Done in #17
