### ISSUE TITLE
Add 'Filters' section

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#14]
At least a simple example of using filters:

- [X] **AngularJS:** (#15)
Filters 
https://docs.angularjs.org/guide/filter

- [X] **Angular:**
Pipes
https://angular.io/guide/pipes

- [X] **React:**
Function invocation

Preferably also with links to docs.

**Comment by ItachiUchiha1998** [comment]
I would like to help with that if its cool..

**Comment by feimosi** [comment]
Great, feel free to make a Pull Request :+1:
