### ISSUE TITLE
Add VueJs

### ISSUE THREAD

**Issue by HendrikGrobler** [feimosi/frameworks-code-comparison#19]
Hi, how do you feel about adding VueJs to this?

I would be willing to create PRs.

**Comment by feimosi** [comment]
That'd be awesome! I was thinking about Vue.js for quite some time.

**Comment by HendrikGrobler** [comment]
Added #20 and #21 so far, will keep adding more as I get time.

**Comment by dillonchanis** [comment]
I can add some examples of Vue as well, I'll tackle Filters first. Maybe show some examples using `render` methods instead of templates.

**Comment by feimosi** [comment]
Nice! Feel free to do so, just agree on who does what so you don't duplicate the work.

**Comment by dillonchanis** [comment]
Awesome, I'll go ahead and get started on the Filter example with Vue and then do a simple example with Lists using `render` rather than the `v-for` directive so someone else could provide that.

**Comment by HendrikGrobler** [comment]
Great! I'm happy to do one for DI, though it's much the same as React in that it doesn't by default really use DI. However it does support dependency injection as per: https://vuejs.org/v2/api/#provide-inject
It also mentions in the docs that it's not really a common use case thing so I'm not sure if I should include it. It mentions something about being similar to React's context which I don't see in the React example.

**Comment by HendrikGrobler** [comment]
Decided to do an example of templates while I wait on feedback for DI, would like some feedback on the wording: #24

**Comment by feimosi** [comment]
Well, then I'd give a basic example similar to React's and mention in one sentence at the bottom:

_There's also [`provide and inject`](https://vuejs.org/v2/api/#provide-inject) mechanism which is primarily provided for advanced plugin / component library use cases._

**Comment by feimosi** [comment]
Hi @HendrikGrobler, any update on DI?

**Comment by HendrikGrobler** [comment]
Hi @feimosi, I've started on it, just had a busy last few days. Will see if I can't finish it tonight.

**Comment by feimosi** [comment]
No problem, just wanted to make sure.

**Comment by feimosi** [comment]
Most of the sections already have Vue examples, so I'm closing the issue. Thank you guys! Feel free to complete the left TODOs if you have time :)
