### ISSUE TITLE
Add 'Inputs and Outputs' section

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#2]
At least one example of each type of binding (with usage):

- [X] **AngularJS:**

```js
bindings {
  user: '<',
  department: '@',
  onEdit: '&',
}
```

- [X] **Angular:** (#7)

```js
  @Input() user: User;
  @Output() onEdit = new EventEmitter<User>();
```

- [X] **React:**

```
propTypes = {
  user: PropTypes.instanceOf(User).isRequired,
  onEdit: PropTypes.func,
}
```

Preferably also with links to docs.

**Comment by devesh-verma** [comment]
@feimosi I would like to work on this but can you please explain what do you want to be done.

**Comment by feimosi** [comment]
Hi, thanks for your interest. There's already one PR (#7) with Angular version, you can prepare examples of AngularJS or React (or even Vue?).

The main idea behind this all is to make it easier for developers to understand differences between frameworks and allow them switch projects with ease.
