### ISSUE TITLE
Add 'Lifecycle methods' section

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#27]
Description of each available method:

- [X]  **AngularJS:**

- [X] **Angular:**

- [X] **React:**

- [X] **Vue.js:**

Preferably also with links to docs.

**Comment by geoffdavis92** [comment]
I'm about to add the `componentDidCatch` method for React 16; are you interested in linking these methods to their documentation, if available?

**Comment by feimosi** [comment]
Sure, that could be useful :+1:

**Comment by geoffdavis92** [comment]
@feimosi added PR #30

**Comment by tesarwijaya** [comment]
hello @feimosi i want to help with vue section. can i?

**Comment by feimosi** [comment]
@tesarwijaya of course, that'd be great!

**Comment by tesarwijaya** [comment]
great! gonna make a PR asap 🚀

**Comment by geoffdavis92** [comment]
Fixed merge conflicts on #30.
