### ISSUE TITLE
Add `Forms` section

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#3]
At least a simple example of using forms (with two-way data binding when available):

- [X] **AngularJS:**
```html
<form name="$ctrl.loginForm">
...
</form>
```

- [X] **Angular:**
```html
<form #loginForm="ngForm">
</form>
```

- [X] **React:**
```jsx
<form onSubmit={this.handleSubmit}>
</form>
```

Preferably also with links to docs.

**Comment by M-ZubairAhmed** [comment]
can i work on this for react form?

**Comment by feimosi** [comment]
Sure! 👍
