### ISSUE TITLE
Add 'Conditional rendering' section

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#32]
At least a simple example of conditional rendering:

- [X]  **AngularJS:**
`ng-if`  
`ng-switch`

- [X] **Angular:**
`*ngIf`  
`[ngSwitch]`

- [X] **React:**

- [ ] **Vue.js:**
`v-if`  
`v-else-if`  
`v-else`

Preferably also with links to docs.

**Comment by sajeetharan** [comment]
i will work on ng-if and ng-switch for angularjs
