### ISSUE TITLE
Add 'Handling Events' section

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#4]
At least a simple example of handling events (component output) :

- [ ] **AngularJS:**
```js
bindings: {
  onClick: '&',
}
// ...
this.onClick({ color: selectedColor })
// ...
<primary-button onClick="$ctrl.changeColor(color)"></button>
```

- [ ] **Angular:**
```js
@Output() onClick = new EventEmitter<string>();
// ...
<Button (onClick)="changeColor($event)">
```
Something about streams

- [ ] **React:**
```jsx
<Button onClick={ this.changeColor } />
```
Something about Synthetic events.

Preferably also with links to docs.

**Comment by vitaliy-bobrov** [comment]
Could I take this one?

**Comment by feimosi** [comment]
Sure!

**Comment by feimosi** [comment]
@vitaliy-bobrov  Any update here?

**Comment by vitaliy-bobrov** [comment]
@feimosi, sorry was busy this days, I'm planning to create pr tomorrow

**Comment by feimosi** [comment]
No problem, thanks!

**Comment by feimosi** [comment]
@vitaliy-bobrov any update?

**Comment by vitaliy-bobrov** [comment]
Sorry, for long waiting time ⏳

**Comment by feimosi** [comment]
Sure, happens to all of us! :sweat_smile:
