### ISSUE TITLE
Add 'Data binding' section

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#43]
At least a simple example of data-binding:

- [X]  **AngularJS:**
`ng-model`

- [X] **Angular:**
`[(ngModel)]`

- [X] **React:**

- [X] **Vue.js:**
`v-model`

Preferably also with links to docs.

https://github.com/feimosi/frameworks-code-comparison#data-binding

**Comment by jcjc712** [comment]
I will work with angular
