### ISSUE TITLE
Convert code snippets indentation to 2 spaces

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#50]
Right now the style is mixed, some snippets are indented with 2 spaces and some with 4.

If you know a tool that would do it automatically, let me know!

**Comment by sergio-alonso** [comment]
Maybe this could help you.

[Markdown code style linter](https://github.com/wooorm/remark-lint)

**Comment by feimosi** [comment]
Looks interesting, but which rule would apply here? I can't find a proper one:
https://github.com/wooorm/remark-lint/blob/master/doc/rules.md

**Comment by yoavmmn** [comment]
HacktoberfestTLV shotgun

**Comment by sergio-alonso** [comment]
I have finally use [textlint](https://github.com/textlint/textlint)

You can see the result in PR https://github.com/feimosi/frameworks-code-comparison/pull/54
