### ISSUE TITLE
Add 'Child nodes' section

### ISSUE THREAD

**Issue by feimosi** [feimosi/frameworks-code-comparison#9]
At least a simple example of using child nodes:

- [ ] **AngularJS:**
`$element`

- [ ] **Angular:**
`ViewChild` and `ContentChild`

- [ ] **React:**
`refs` and `this.props.children`

Preferably also with links to docs.

**Comment by andrevargas** [comment]
Hello! I'd like to take this one! 😊

**Comment by feimosi** [comment]
Cool! Feel free to do it 😄
